language: python
python:
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install codecov
script:
  - wget https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/bin/chromedriver
  - sudo chown root:root /usr/bin/chromedriver
  - sudo chmod +x /usr/bin/chromedriver
  - coverage run -m unittest
