language: python
python:
  - "3.6"
cache: pip
sudo: required
addons: # get google-chrome-stable
  chrome: stable
install: # Install ChromeDriver (64bits; replace 64 with 32 for 32bits).
  - wget -N https://chromedriver.storage.googleapis.com/73.0.3683.20/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  - pip install -r requirements.txt
  - pip install codecov
script:
  - whereis google-chrome-stable
  - whereis chromedriver
  - coverage run -m unittest
